name: Build OmarC Plugins

concurrency: 
  group: "omarc-build"
  cancel-in-progress: true

on:
  push:
    branches:
      - arabseed
      - master
      - main
    paths:
      - 'omarC/**'
      - '.github/workflows/omarc_build.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout builds
        uses: actions/checkout@v3
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: |
          cd omarC
          chmod +x gradlew
          ./gradlew make makePluginsJson
          
          # Copy artifacts to builds folder
          # Note: omarC/build/plugins.json and omarC/*/build/*.cs3
          
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/
          cp build/plugins.json $GITHUB_WORKSPACE/builds/ || true

      - name: Push builds
        run: |
          cd builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build omarC $GITHUB_SHA" --allow-empty
          git push
